version: '3'

services:


  web:
    image: python:3.8-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.services.web-service.loadbalancer.server.port=5000"
    volumes:
      - ./web:/app
    working_dir: /app
    command: ["sh", "-c", "pip install -r requirements.txt && python app.py"]

  data-generator:
    image: python:3.8-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.data-generator.rule=Host(`localhost`)"
      - "traefik.http.services.data-generator-service.loadbalancer.server.port=5001"
    volumes:
      - ./data-generator:/app
    working_dir: /app
    command: ["sh", "-c", "pip install -r requirements.txt && python data_generator.py"]


